version: '3'
services:
  romm:
    image: ghcr.io/rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    ports:
      - "8091:8080"
    environment:
      - ROMM_DB_DRIVER=sqlite
    volumes:
      - P:/gaming/roms/data:/romm/resources
      - P:/gaming/roms/library:/romm/library
      - P:/gaming/roms/config:/romm/config
networks:
  default:
    name: proxion-network
    external: true
