version: '3'
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    restart: unless-stopped
    ports:
      - "8092:80"
      - "3008:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - P:/gaming/emulators/config:/config
      - P:/gaming/emulators/data:/data
networks:
  default:
    name: proxion-network
    external: true
