# Mastodon Proxion Binding
services:
  web:
    volumes:
      - P:/social/mastodon/system:/mastodon/public/system
  sidekiq:
    volumes:
      - P:/social/mastodon/system:/mastodon/public/system
  db:
    volumes:
      - P:/social/mastodon/postgres:/var/lib/postgresql/data
  redis:
    volumes:
      - P:/social/mastodon/redis:/data
