version: '3.1'
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - "8089:2368"
    environment:
      # use the database we created
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=ghost
      - database__connection__database=ghost
      - url=http://localhost:8089
    volumes:
      - ./content:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ghost
    volumes:
      - ./db:/var/lib/mysql
