version: '3.2'
services:
    changedetection:
        image: dgtlmoon/changedetection.io:latest
        restart: always
        ports:
            - "8091:5000"
        volumes:
            - ./datastore:/datastore
        environment:
            - BASE_URL=http://localhost:8091
            - PLAYWRIGHT_DRIVER_URL=ws://playwright:3000
        depends_on:
            - playwright

    playwright:
        image: browserless/chrome:latest
        restart: always
        ports:
            - "3333:3000"
