version: '3'
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    ports:
      - "9091:9091"
    volumes:
      - P:/security/authelia/config:/config
    environment:
      - TZ=UTC
networks:
  default:
    name: proxion-network
    external: true
