version: '3'

services:
  cryptpad:
    image: "promasu/cryptpad:latest" # Using a popular community docker image for CryptPad
    container_name: cryptpad
    environment:
      - CPAD_DOMAIN=http://localhost:3001
    ports:
      - "3001:3000"
    volumes:
      - ./data/blob:/cryptpad/blob
      - ./data/block:/cryptpad/block
      - ./data/customize:/cryptpad/customize
      - ./data/data:/cryptpad/data
      - ./data/datastore:/cryptpad/datastore
    restart: unless-stopped
