version: '3'
services:
  pialert:
    container_name: pialert
    image: joke2k/pialert:latest
    restart: unless-stopped
    environment:
      - TZ=UTC
    network_mode: host
    volumes:
      - P:/security/pialert/config:/home/pi/pialert/config
      - P:/security/pialert/db:/home/pi/pialert/db
