version: '3'
services:
  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    ports:
      - "8065:8065"
    volumes:
      - P:/social/mattermost/config:/mattermost/config
      - P:/social/mattermost/data:/mattermost/data
      - P:/social/mattermost/logs:/mattermost/logs
      - P:/social/mattermost/plugins:/mattermost/plugins
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
    depends_on:
      - db
  db:
    container_name: mattermost-db
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    volumes:
      - P:/social/mattermost/db:/var/lib/postgresql/data
networks:
  default:
    name: proxion-network
    external: true
