version: "3"
services:
  adguardhome:
    build:
      context: .
      dockerfile: Dockerfile.hardened
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "853:853/tcp"
      - "784:784/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "127.0.0.1:3055:3000/tcp" # Setup/UI
    volumes:
      - ../../proxion-core/storage/network/adguard/work:/opt/adguardhome/work
      - ../../proxion-core/storage/network/adguard/conf:/opt/adguardhome/conf
