version: '3'
services:
  kasm:
    image: kasmweb/kasm:1.15.0
    container_name: kasm
    privileged: true
    restart: unless-stopped
    ports:
      - "6901:6901"
    environment:
      - KASM_PORT=6901
    volumes:
      - P:/system/workspaces/data:/data
      - P:/system/workspaces/profiles:/profiles
networks:
  default:
    name: proxion-network
    external: true
