version: '3'
services:
  pds:
    image: ghcr.io/bluesky-social/pds:latest
    container_name: bluesky-pds
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      - PDS_HOSTNAME=localhost
      - PDS_JWT_SECRET=proxion-secret-atproto
    volumes:
      - P:/web/atproto/data:/pds/data
networks:
  default:
    name: proxion-network
    external: true
