version: '3'
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    build:
      context: .
      dockerfile: Dockerfile.hardened
    build:
      context: .
      dockerfile: Dockerfile.hardened
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - P:/media/subtitles/config:/config
      - P:/media/movies:/movies
      - P:/media/tv:/tv
    ports:
      - "6767:6767"
networks:
  default:
    name: proxion-network
    external: true
