version: '3.3'

services:
  fireflydb:
    image: mariadb:10
    container_name: firefly_db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped

  fireflyapp:
    image: fireflyiii/core:latest
    container_name: firefly_app
    depends_on:
      - fireflydb
    environment:
      - APP_KEY=${APP_KEY}
      - DB_HOST=fireflydb
      - DB_PORT=3306
      - DB_CONNECTION=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=UTC
    ports:
      - "8080:8080"
    volumes:
      - ./upload:/var/www/html/storage/upload
    restart: unless-stopped
