version: '3'
services:
  stirling-pdf:
    image: frostandard/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - P:/office/pdf-tools/trainingData:/usr/share/tesseract-ocr/4.00/tessdata
      - P:/office/pdf-tools/extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
networks:
  default:
    name: proxion-network
    external: true
