version: '3'
services:
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    restart: unless-stopped
    ports:
      - "5801:5800"
    volumes:
      - P:/web/browser/config:/config
networks:
  default:
    name: proxion-network
    external: true
