version: '3'
services:
  pixelfed:
    image: pixelfed/pixelfed:latest
    container_name: pixelfed
    restart: unless-stopped
    ports:
      - "8095:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=pixelfed-db
    volumes:
      - P:/social/pixelfed/storage:/var/www/storage
    depends_on:
      - pixelfed-db
  pixelfed-db:
    image: mysql:8
    container_name: pixelfed-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=pixelfed
      - MYSQL_USER=pixelfed
      - MYSQL_PASSWORD=pixelfed
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - P:/social/pixelfed/db:/var/lib/mysql
networks:
  default:
    name: proxion-network
    external: true
