version: '3'
services:
  jitsi:
    image: jitsi/web:latest
    container_name: jitsi
    restart: unless-stopped
    ports:
      - "8087:80"
      - "8444:443"
    environment:
      - TZ=UTC
      - PUBLIC_URL=http://localhost:8087
    volumes:
      - P:/social/jitsi/config:/config
networks:
  default:
    name: proxion-network
    external: true
