version: '3'
services:
  overseerr:
    image: sgeto/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - P:/media/requests:/app/config
    ports:
      - "5055:5055"
networks:
  default:
    name: proxion-network
    external: true
