version: '3'
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    restart: unless-stopped
    ports:
      - "3007:3333"
    environment:
      - NODE_ENV=production
      - JWT_SECRET_KEY=proxion-secret
    volumes:
      - P:/finance/investments/data:/app/data
networks:
  default:
    name: proxion-network
    external: true
