version: '3'
services:
  kavita:
    image: jvm602/kavita:latest
    container_name: kavita
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - P:/media/comics/manga:/manga
      - P:/media/comics/comics:/comics
      - P:/media/comics/config:/kavita/config
    ports:
      - "5001:5000"
networks:
  default:
    name: proxion-network
    external: true
