version: '3'
services:
  actual:
    image: ghcr.io/actualbudget/actual-server:latest
    container_name: actual
    restart: unless-stopped
    ports:
      - "5006:5006"
    volumes:
      - P:/finance/budget/data:/data
networks:
  default:
    name: proxion-network
    external: true
