version: '3'
services:
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped
    ports:
      - "3012:3001"
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_ENABLE_HOST_NETWORK=false
      - DASHDOT_PORT=3012
networks:
  default:
    name: proxion-network
    external: true
