version: '3'
services:
  steam-headless:
    image: jlesage/steam-headless:latest
    container_name: steam-headless
    restart: unless-stopped
    ports:
      - "5800:5800"
    environment:
      - VNC_PASSWORD=proxion-gamer
    volumes:
      - P:/gaming/steam/config:/config
      - P:/gaming/steam/games:/mnt/games
networks:
  default:
    name: proxion-network
    external: true
