version: '3'
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    restart: unless-stopped
    ports:
      - "3006:3000"
    volumes:
      - P:/web/bookmarks/data:/data
    environment:
      - NEXTAUTH_SECRET=proxion-secret
      - DATABASE_URL=postgresql://linkwarden:password@db:5432/linkwarden
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=linkwarden
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=linkwarden
    volumes:
      - P:/web/bookmarks/db:/var/lib/postgresql/data
networks:
  default:
    name: proxion-network
    external: true
