version: '3'

services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    ports:
      - "8581:8581"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./config:/homebridge
