version: '2.4'

services:
  archivebox:
    image: archivebox/archivebox:latest
    restart: always
    ports:
      - "8090:8000"
    environment:
      - ALLOW_ENTITY_SUBSTITUTION=True
      - MEDIA_MAX_SIZE=750m
      - TIMEOUT=60
    volumes:
      - ./data:/data
