version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - P:/system/dashboard/configs:/app/data/configs
      - P:/system/dashboard/icons:/app/public/icons
      - P:/system/dashboard/data:/data
    ports:
      - "3003:7575"
    environment:
      - TZ=UTC
networks:
  default:
    name: proxion-network
    external: true
